
device: cuda
enable_display: true

detection:
  model_path: yolo11n.pt
  conf_threshold: 0.3
  iou_threshold: 0.55
  conf_high: 0.8
  conf_medium: 0.3
  use_tensorrt: true 

reid:
  model_path: reid_ltcc.engine
  embedding_dim: 2048
  batch_size: 2
  image_size_h: 384
  image_size_w: 192
  use_tensorrt: true
  tensorrt_precision: fp16

gallery:
  max_size: 500
  buffer_capacity: 10
  similarity_threshold_match: 0.50  
  similarity_threshold_new: 0.70  
  quality_admission_threshold: 0.91
  ttl_frames_crowded: 30
  ttl_frames_sparse: 150
  ema_alpha_high_conf: 0.3
  ema_alpha_low_conf: 0.1

queues:
  input_queue_size: 15       # Was 30 (Original: 10)
  processing_queue_size: 30  # Was 100 (Original: 50)
  output_queue_size: 30      # Was 50 (Original: 20)

monitoring:
  enable_monitoring: true
  metrics_update_interval: 1.0
  log_level: INFO
  save_stats: true
  stats_save_interval: 100

degradation:
  enable_degradation: true
  gpu_threshold_tier1: 0.85
  gpu_threshold_tier2: 0.9
  memory_threshold_tier1: 0.85
  memory_threshold_tier2: 0.9
  queue_depth_threshold: 15 